version: "3.3"
services:
  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ~/apps/mongo:/data/db

volumes:
  mongodb-data: {}